name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS) + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # use 9 if your lockfile is v9; use 8 if your repo uses pnpm 8
          version: 9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      # Vitest coverage + reporters for artifact & summary
      - name: Test with coverage
        run: pnpm run test -- --coverage --coverage.reporter=lcov --coverage.reporter=text-summary --coverage.reporter=json-summary

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          if-no-files-found: error

      - name: Add coverage to PR summary
        if: always()
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            node -e "const s=require('./coverage/coverage-summary.json').total; \
            const rows=Object.entries(s).map(([k,v])=>`| ${k} | ${v.pct}% | ${v.covered}/${v.total} |`).join('\n'); \
            console.log('**Coverage summary**\n\n| Metric | % | Covered/Total |\n|---|---:|---:|\n'+rows);" \
            >> $GITHUB_STEP_SUMMARY
          else
            echo 'No coverage summary found.' >> $GITHUB_STEP_SUMMARY
          fi
