name: CI
on:
  pull_request: { branches: [main] }
  push:        { branches: [main] }
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make pnpm available BEFORE setup-node tries to cache it
      - name: Enable pnpm (Corepack)
        run: |
          corepack enable
           corepack prepare pnpm@10 --activate
          pnpm -v

      # Now it's safe to use cache: pnpm
      - name: Setup Node (LTS) + cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      - name: Unit tests
        run: pnpm run test
